# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                frontend/src/client/.*|
                backend/app/email-templates/build/.*
            )$
      - id: trailing-whitespace
        exclude: ^frontend/src/client/.*
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        types: [text]
        files: ^frontend/

      - id: alembic-check
        name: alembic check (detect migration drift)
        entry: bash -c 'cd backend && uv run alembic check'
        language: system
        pass_filenames: false
        files: ^backend/app/(models\.py|alembic/versions/.*\.py)$

      - id: alembic-migration-safety
        name: alembic migration safety (prevent data loss)
        entry: python backend/scripts/check_migration_safety.py
        language: system
        pass_filenames: false
        files: ^backend/app/alembic/versions/.*\.py$

      - id: docs-no-downgrade
        name: docs safety (no alembic downgrade in docs)
        entry: python scripts/check_docs_no_downgrade.py
        language: system
        pass_filenames: false
        files: ^docs/.*\.md$

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
