name: Lint Backend

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.4.15"
          enable-cache: true
      - name: Install dependencies
        run: uv sync
        working-directory: backend
      - name: Run linters
        run: uv run bash scripts/lint.sh
        working-directory: backend
        env:
          # Required env vars for Settings class initialization during mypy analysis
          PROJECT_NAME: CurriculumExtractor
          SECRET_KEY: just-for-linting
          FIRST_SUPERUSER: admin@example.com
          FIRST_SUPERUSER_PASSWORD: just-for-linting
          DATABASE_URL: postgresql+psycopg://postgres:password@localhost:5432/app
          SUPABASE_URL: https://dummy.supabase.co
          SUPABASE_ANON_KEY: dummy-anon-key
          SUPABASE_SERVICE_KEY: dummy-service-key
          REDIS_PASSWORD: dummy-redis-password
          REDIS_URL: redis://:dummy@localhost:6379/0
          CELERY_BROKER_URL: redis://:dummy@localhost:6379/0
          CELERY_RESULT_BACKEND: redis://:dummy@localhost:6379/0
